// Copyright 2013 The Flutter Authors
// Use of this source code is governed by a BSD-style license that can be
// found in the LICENSE file.
// Autogenerated from Pigeon (v26.3.4), do not edit directly.
// See also: https://pub.dev/packages/pigeon

@import Foundation;

@protocol FlutterBinaryMessenger;
@protocol FlutterMessageCodec;
@class FlutterError;
@class FlutterStandardTypedData;

NS_ASSUME_NONNULL_BEGIN

@class FVPMediaSelectionAudioTrackData;
@class FVPNotificationMetadataMessage;
@class FVPBackgroundPlaybackMessage;

/// Raw audio track data from AVMediaSelectionOption (for HLS streams).
@interface FVPMediaSelectionAudioTrackData : NSObject
/// `init` unavailable to enforce nonnull fields, see the `make` class method.
- (instancetype)init NS_UNAVAILABLE;
+ (instancetype)makeWithIndex:(NSInteger)index
                  displayName:(nullable NSString *)displayName
                 languageCode:(nullable NSString *)languageCode
                   isSelected:(BOOL)isSelected
          commonMetadataTitle:(nullable NSString *)commonMetadataTitle;
@property(nonatomic, assign) NSInteger index;
@property(nonatomic, copy, nullable) NSString *displayName;
@property(nonatomic, copy, nullable) NSString *languageCode;
@property(nonatomic, assign) BOOL isSelected;
@property(nonatomic, copy, nullable) NSString *commonMetadataTitle;
@end

/// Metadata for the system media notification when playing in background.
@interface FVPNotificationMetadataMessage : NSObject
/// `init` unavailable to enforce nonnull fields, see the `make` class method.
- (instancetype)init NS_UNAVAILABLE;
+ (instancetype)makeWithId:(NSString *)id
                     title:(nullable NSString *)title
                     album:(nullable NSString *)album
                    artist:(nullable NSString *)artist
                durationMs:(nullable NSNumber *)durationMs
                    artUri:(nullable NSString *)artUri;
@property(nonatomic, copy) NSString *id;
@property(nonatomic, copy, nullable) NSString *title;
@property(nonatomic, copy, nullable) NSString *album;
@property(nonatomic, copy, nullable) NSString *artist;
@property(nonatomic, strong, nullable) NSNumber *durationMs;
@property(nonatomic, copy, nullable) NSString *artUri;
@end

/// Message for configuring background playback with media notification.
@interface FVPBackgroundPlaybackMessage : NSObject
/// `init` unavailable to enforce nonnull fields, see the `make` class method.
- (instancetype)init NS_UNAVAILABLE;
+ (instancetype)makeWithEnableBackground:(BOOL)enableBackground
                    notificationMetadata:
                        (nullable FVPNotificationMetadataMessage *)notificationMetadata;
@property(nonatomic, assign) BOOL enableBackground;
@property(nonatomic, strong, nullable) FVPNotificationMetadataMessage *notificationMetadata;
@end

/// The codec used by all APIs.
NSObject<FlutterMessageCodec> *FVPGetVideoPlayerInstanceMessagesCodec(void);

@protocol FVPVideoPlayerInstanceApi
- (void)setLooping:(BOOL)looping error:(FlutterError *_Nullable *_Nonnull)error;
- (void)setVolume:(double)volume error:(FlutterError *_Nullable *_Nonnull)error;
- (void)setPlaybackSpeed:(double)speed error:(FlutterError *_Nullable *_Nonnull)error;
- (void)playWithError:(FlutterError *_Nullable *_Nonnull)error;
/// @return `nil` only when `error != nil`.
- (nullable NSNumber *)position:(FlutterError *_Nullable *_Nonnull)error;
- (void)seekTo:(NSInteger)position completion:(void (^)(FlutterError *_Nullable))completion;
- (void)pauseWithError:(FlutterError *_Nullable *_Nonnull)error;
- (void)disposeWithError:(FlutterError *_Nullable *_Nonnull)error;
/// @return `nil` only when `error != nil`.
- (nullable NSArray<FVPMediaSelectionAudioTrackData *> *)getAudioTracks:
    (FlutterError *_Nullable *_Nonnull)error;
- (void)selectAudioTrackAtIndex:(NSInteger)trackIndex
                          error:(FlutterError *_Nullable *_Nonnull)error;
- (void)startPictureInPicture:(FlutterError *_Nullable *_Nonnull)error;
- (void)stopPictureInPicture:(FlutterError *_Nullable *_Nonnull)error;
- (void)setAutoPictureInPicture:(BOOL)enabled error:(FlutterError *_Nullable *_Nonnull)error;
@end

extern void SetUpFVPVideoPlayerInstanceApi(id<FlutterBinaryMessenger> binaryMessenger,
                                           NSObject<FVPVideoPlayerInstanceApi> *_Nullable api);

extern void SetUpFVPVideoPlayerInstanceApiWithSuffix(
    id<FlutterBinaryMessenger> binaryMessenger, NSObject<FVPVideoPlayerInstanceApi> *_Nullable api,
    NSString *messageChannelSuffix);

NS_ASSUME_NONNULL_END
